default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  <<: *default
  database: clientfinder_production
  username: tomlee
  password:

development:
  <<: *default
  database: clientfinder_development
  username: tomlee
  password:

test:
  <<: *default
  database: clientfinder_test
  username: tomlee
  password:
