# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79a10f1d7ec89349042b47667a331a8a0aaa2cb794cd6920d8118765249682bdb6ad9dc669fd07a0b7878be35011c0679ee07c9697677d93b4e67f47c011deb9

test:
  secret_key_base: 1df78f0671f9529909a20b8b61682eab76e91c45bd257600525195040ff6d23b7bfef43431cc2c9efef5e000ae29eecf78ae49ee9db03ebe4b55e734917dcd89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
